on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

name: Check

jobs:
  test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14,16,18]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: yarn install
      - run: yarn run build --noEmit
      - run: yarn run test
